Merge feature to master
harshdeepkanhai/the-next-web-clone pull request #1
Opened 2020-08-12 15:12 UTC by harshdeepkanhai

- 

- Make site responsive 

-  for mobile, tablets and pc

2020-08-18 17:42 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project it's looking really good, however, in order to accomplish as the actual page, you required to do these changes, listed below:
- [x] Improve the description text and title of your pull request
- [x] In medium screens, TWN logo sholud go to the leftmost part of the page
<table>
 <tr>
 <th>Yours</th>
 <th>Original</th>
 </tr>
 <tr>
 <td><img src="https://user-images.githubusercontent.com/56762529/90541172-9ae08b00-e158-11ea-82fd-3bff7068553f.png"></td>
 <td><img src="https://user-images.githubusercontent.com/56762529/90541238-b0ee4b80-e158-11ea-9dd0-aa93a25ad9c7.png"></td>
 </tr>
</table>

### The main goal of this project is to make that clone page responsive, and in order to achieve that:
- [x] Your columns and layout of all three viewports (small, medium and large) should be equal to the original one, you page is facing some overlapping. Check the pointers below:
<table>
 <tr>
 <th>Yours</th>
 <th>Original</th>
 </tr>
 <tr>
 <th>Large (1024px)</th>
 <th>Large (1024px)</th>
 </tr>
 <tr>
 <td> Overlapping
<img src="https://user-images.githubusercontent.com/56762529/90550222-04b36180-e166-11ea-86dc-54369e6f7a2f.png"></td>
 <td><img src="https://user-images.githubusercontent.com/56762529/90551748-2f061e80-e168-11ea-9bac-9c1fe855c007.png"></td>
 </tr>
 <tr>
 <th>Medium (768px)</th>
 <th>Medium (768px)</th>
 </tr>
 <tr>
 <td>Here, we also have overlapping and in the main three articles, the bigger article isn't the biggest <img src="https://user-images.githubusercontent.com/56762529/90552683-95d80780-e169-11ea-974e-ea1951a28e55.png"></td>
 <td><img src="https://user-images.githubusercontent.com/56762529/90551443-b901b780-e167-11ea-9e33-3f18745e7259.png"></td>
 </tr>
<th>Small (375px)</th>
 <th>Small (375px)</th>
 </tr>
 <tr>
 <td>Still overlapping and  at the footer, we have some empty space <img src="https://user-images.githubusercontent.com/56762529/90551074-30831700-e167-11ea-86a5-65f10576ad02.png"></td>
 <td><img src="https://user-images.githubusercontent.com/56762529/90544483-910d5680-e15d-11ea-923f-c08c7634b382.png"></td>
 </tr>
</table>
As you can see, in the small and medium sizes, your page isn't breaking, as it should. Is overlaping 

- [ ] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))
![image](https://user-images.githubusercontent.com/56762529/90545855-a08d9f00-e15f-11ea-9787-641d59a10e5c.png)
(mobile.css)
![image](https://user-images.githubusercontent.com/56762529/90545972-d16dd400-e15f-11ea-831b-3fcf9bd6ed70.png)
(main.css)
Tip: You should check for repeated code and remove it whenever possible! E.g.: Instead of having font-weigth: bold repeated 15x, create only one class like this: `.f-bold { font-weigth: bold }` and use that same class when you need it.
- [x] Your code is throwing some warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them
![image](https://user-images.githubusercontent.com/56762529/90546174-14c84280-e160-11ea-9c17-50444b396167.png)


## Tip: Take a take a look 👀 in your `@media queries`, (check the breaking points) if you need any some reference use [this](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) link

**Please make the required changes and resubmit for a new code review once you are ready**

As always, I wish you all the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-21 22:56 UTC, SpaYco requested changes
# Changes Requested 

Hello Team! 👋 

Awesome job so far!! 👍 you still need to make some changes though! 

I attached the changes down below 👇 🙃 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-21 22:56 UTC, SpaYco commented on index.html
> +        </section>
- [x] on medium and small screens this becomes only 3 cards instead of 4 

| Yours | Original |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/11758151/90940957-85918800-e408-11ea-8e37-cca4bebdc96b.png) | ![image](https://user-images.githubusercontent.com/11758151/90940968-8f1af000-e408-11ea-8d80-422c17fe3c89.png) |

2020-08-21 22:56 UTC, SpaYco commented on index.html
> +                        email</a> |
- [x] This is not aligned well on Medium screens

| Yours | Original |
|------|------|
| ![image](https://user-images.githubusercontent.com/11758151/90941063-f5077780-e408-11ea-843e-b4ad3a3c9892.png) | ![image](https://user-images.githubusercontent.com/11758151/90941078-02bcfd00-e409-11ea-8ee9-9f343a1d0c64.png) |

2020-08-24 13:46 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @harshdeepkanhai  @jonathastavares** 
Good job with your new submission for this project :muscle:  :muscle:
There are some improvements to do before you can go ahead:
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition.
- [x]  In medium screen size, the TNW logo should disappear:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/c8Plejol.png) | ![image](https://i.imgur.com/3PJ4WQGl.png) |

- [x] remove the underline of your links in the navbar:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/YEeBRiMl.png) | ![image](https://i.imgur.com/NviHFgBl.png) |

- [x] In the footer, one of the icons is missing

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/xbtpWNcl.png) | ![image](https://i.imgur.com/V2rdPCEl.png) |

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/main.css
> +  }
Group selectors on lines 141 and 153

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/main.css
> +  }
Group selectors on lines 290 and 299

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/medium.css
> +  }
Group selectors on lines 50 and 64

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/medium.css
> +  }
Group selectors on lines 40, 68 and 267

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/medium.css
> +  }
Group selectors on lines 2, 182, 195 and 298

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/medium.css
> +  }
Group selectors with the same style definition

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/mobile.css
> +  }
Group selectors on lines 175, 189 and 298

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/mobile.css
> +  }
Group selectors with the same style definition

2020-08-24 13:46 UTC, andresporras3423 commented on assets/stylesheets/mobile.css
> +  }
Group selectors on lines 248 and 435

2020-08-24 17:42 UTC, kubilaycaglayan approved these changes
Hello Team :wave: 
Status: Project Approved :green_circle: 

Congratulations on doing all the changes! :star2:  :boom: 

With all my respect...

2020-08-24 17:59 UTC, merged